FROM alpine:latest

RUN apk add --no-cache \
    curl \
    tzdata

ENV TZ=Asia/Jakarta

COPY cronjob.sh /cronjob.sh

RUN chmod +x /cronjob.sh

RUN echo "55 23 * * * /cronjob.sh >> /var/log/cron.log 2>&1" > /etc/crontabs/root

CMD ["crond", "-f", "-l", "2"]